// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGvd3nFHeQwHjbpt-qJcf9a7XgvLU6I0w',
    appId: '1:453930433024:web:a7a04e0b46c5f51ec0f6e5',
    messagingSenderId: '453930433024',
    projectId: 'egme-investigation',
    authDomain: 'egme-investigation.firebaseapp.com',
    storageBucket: 'egme-investigation.appspot.com',
    measurementId: 'G-GBPMT66FQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQ8YBlsuyFnHsl_ta1R1NLrhh7SwE3wU',
    appId: '1:453930433024:android:2cf2b91bb398cae8c0f6e5',
    messagingSenderId: '453930433024',
    projectId: 'egme-investigation',
    storageBucket: 'egme-investigation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-mwMk4xFcFvn89zdCRcfTDVr8eSeLoo0',
    appId: '1:453930433024:ios:57f40a13fcf5cf8ac0f6e5',
    messagingSenderId: '453930433024',
    projectId: 'egme-investigation',
    storageBucket: 'egme-investigation.appspot.com',
    iosBundleId: 'com.example.emge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-mwMk4xFcFvn89zdCRcfTDVr8eSeLoo0',
    appId: '1:453930433024:ios:1d6fe06c6d13275dc0f6e5',
    messagingSenderId: '453930433024',
    projectId: 'egme-investigation',
    storageBucket: 'egme-investigation.appspot.com',
    iosBundleId: 'com.example.emge.RunnerTests',
  );
}
